### ISSUE TITLE
Naming is hard, need help

### ISSUE THREAD

**Issue by nyurik** [gquintard/varnish-rs#104]
@gquintard I need your naming skills for the few leftover items.... but make sure your Rust hat is on... not the C one :)

* `VSC` -> `Statistics` (?)
* `VSCInternal` -> `StatsInt`  /  `StatsImpl` / ...?
* `VSCBuilder` -> ?
* `VSCBulder::build` -> `attach` -- I think build is a bit confusing here (funny - in this case I actually am siding with the internal Varnish naming)
* `vsm_error` -> ?

This is a followup from #39

**Comment by gquintard** [comment]
I'd go with `Stats`; ` StatsImpl` is ok, I don't think it's `pub` anyway.
`vsm_error` -> `VSMError`?
