### ISSUE TITLE
Add support for Varnish 6.0 (LTS)

### ISSUE THREAD

**Issue by teqm** [gquintard/varnish-rs#18]
Right now the bindings aren't compatible with LTS version of Varnish (which also the enterprise version is based on). I've made some changes that would provide such support, you can check it out here https://github.com/teqm/varnish-rs/tree/6.0. I didn't make the PR yet as I don't want to merge it to `main` and I'd rather have a separate branch for each version of varnish (the same way as it's done e.g. here https://github.com/varnish/varnish-modules). Also the compatibility "fixes" I made are somewhat naive :sweat_smile: as I removed a lot of "problematic" code because of different or non existent vmod APIs - but I guess that might be fine and such support could be introduced (or rather brought back) later on :thinking:.

thoughts @gquintard?

**Comment by gquintard** [comment]
Hi @teqm!

I'm super happy to have a `6.0` branch, even with reduced capabilities. open that PR :-) (if you need me to create the branch first, please let me know).

The two things I wonder about it are:
- do we want to push the `6.0` version(s) to crates.io?
- if so, what does the versioning look like? We might have to start using the minor to track the varnish version (all `0.1.x` would be for `6.0`, `0.2.x` for 7.2, `0.3.x` for the next varnish version, etc.)

In general, I'm fairly okay with not supporting older versions, so I'm not sure we need branch for every single versions, but LTS is definitely an important one.

**Comment by teqm** [comment]
> I'm super happy to have a 6.0 branch, even with reduced capabilities. open that PR :-) (if you need me to create the branch first, please let me know).

yeah, if that's not an issue please create a branch🙏 

> The two things I wonder about are:
>
> do we want to push the 6.0 version(s) to crates.io?
if so, what does the versioning look like? We might have to start using the minor to track the varnish version (all 0.1.x would be for 6.0, 0.2.x for 7.2, 0.3.x for the next varnish version, etc.)
In general, I'm fairly okay with not supporting older versions, so I'm not sure we need branch for every single versions, but LTS is definitely an important one.

it would be nice to have it published and properly versioned, but yeah that can be tough / cumbersome 🤔- if `varnish-rs` was stable then we could use major to indicate support for different versions of varnish (aka breaking changes) - but abusing minor for the same purpose doesn't sound perfect ;/ (would work just fine though)

Other option could be to rename the crates (in 6.0 branch) to something like
- `varnish` -> `varnish60` ,
- `varnish-sys` -> `varnish-sys60` 

and publish separately from the existing ones.

I think I like the last option, but I'm not sure how hard would that be to maintain (it shouldn't be an issue for vmod authors as they could alias the dependency to the old name) - wdyt @gquintard?

**Comment by gquintard** [comment]
`6.0` branch is in!

I'm a bit worried about the `varnish60`, it will work fine once, but that feel a bit disrespectful to the ecosystem to multiply crates like that, and also, that really expose us to name squatting.

There's also a "fun" versioning scheme we could use `0.720`.x for `7.2` and `0.600.x` for `6.0`. That makes the matching version fairly obvious, keeps the versions ordered, doesn't break semver, and we'd be fine as long as Varnish keeps its minors under 100.

you know what? For now, let's sleep on it, we don't *have to* publish that crate version, worst case scenario people can vendor it (I don't want that, but at least there's an escape hatch)

**Comment by teqm** [comment]
> 6.0 branch is in!

thanks!

> you know what? For now, let's sleep on it, we don't have to publish that crate version, worst case scenario people can vendor it (I don't want that, but at least there's an escape hatch)

yeah, it's not like we have to figure it out now :D - anyway, I've pushed out the PR, please let me know if you need more info from me :bow:
