### ISSUE TITLE
support varnishtest skipping test

### ISSUE THREAD

**Issue by gquintard** [gquintard/varnish-rs#22]
if a test is skipped, we currently fail it because the return code isn't 0.

Minimal example:

```
varnishtest "skip"
feature cmd "non-existing command"
```

**Comment by nyurik** [comment]
How does test skipping works?  I don't see any magical `"skip"` or `feature` commands in the [docs](https://www.varnish-software.com/developers/tutorials/testing-varnish-varnishtest/) - what would be the indication that the test should be skipped?

**Comment by gquintard** [comment]
that's an `autotool` behavior, if the return code is 77, the test was skipped. Example:
```
$ cat foo.vtc 
varnishtest "skip test"
feature cmd false
$ varnishtest foo.vtc 
#    top  TEST foo.vtc skipped (0.070)
$ echo $?
77
```
