### ISSUE TITLE
Reformat code with `cargo fmt`

### ISSUE THREAD

**Issue by nyurik** [gquintard/varnish-rs#29]
It is a bit hard to read when code does not follow conventions used by most other Rust projects - please consider running `cargo fmt` on all of it. I know it could be a bit annoying at first if you are used to other style, but it helps newcomers to not stumble over unusual syntax. Plus some IDEs are often pre-set to autoformat on save, so a dev would be fighting it.  Thx!

**Comment by gquintard** [comment]
when you are right, you're right, no denying it. I've run it just now, and I'll try to be more diligent in the future

**Comment by nyurik** [comment]
Thanks!  Most CIs actually do a `cargo fmt -- --check` to ensure it is always in a good state - do you perhaps want to add that?

**Comment by gquintard** [comment]
sounds like a good way forward, yes!
