### ISSUE TITLE
Consider merging varnish-sys into varnish crate

### ISSUE THREAD

**Issue by nyurik** [gquintard/varnish-rs#32]
This is more of a question - would it make sense to merge -sys into the main crate?  It seems most of its content is auto-generated anyway, so might as well just move the build.rs to the root?  I think -sys creates mostly exist only when they are being maintained separately by hand, rather than being auto-genned.

**Comment by gquintard** [comment]
what I've seen, it's customary to have two crates, notable in case someone doesn't want to embark the manually crafted bindings, so I would lean towards no, but I'm open to discussions

**Comment by nyurik** [comment]
Hi, thx for replying. I am not certain I understood what you meant.  Most of the -sys crates I have seen are all manually maintained. I haven't yet seen a single one (i'm sure they exist) - that is fully auto-generated, esp when only used by one other crate. Having two crates is tricky to manage, esp because crates.io does not yet support multi-crate publishing.

**Comment by gquintard** [comment]
that's a good data, I had a cursory look a while back and understood that the C interfaces where usually isolated in a `-sys` crate, but maybe we can just use a module and be done with it.

it's not a priority, but if you want to merge them, I'm not against it

**Comment by gquintard** [comment]
done through #34
