### ISSUE TITLE
Rename all re-exported types and enum values

### ISSUE THREAD

**Issue by nyurik** [gquintard/varnish-rs#39]
Using non-conventional naming tends to get in the way of using a new project (hence the convention :) ) - Since we now moved all varnish_sys into the main crate, and hopefully will rename it to `ffi` submodule, I propose rename all public interfaces to be consistent with the expected Rust naming rules.

Apparently Bindgen [supports](https://github.com/rust-lang/rust-bindgen/discussions/2514) it too.

**Comment by gquintard** [comment]
depends on how much manual work, but no big objection

**Comment by nyurik** [comment]
I guess it is better to keep the ffi names as is *unless* they are exposed externally (except in the `ffi` module).  Note that ideally `ffi` mod should not be public at all - the whole idea of a rust lib like this is to re-export everything unsafe as safe.  So the ideal state would be no unsafe public API at all.

**Comment by gquintard** [comment]
yes, that's how I see it, `ffi` should just be an escape hatch in case something is not covered, or if you want to do gnarly stuff and poke at the Varnish internals yourself.

**Comment by nyurik** [comment]
sounds good - which means it should probably be hidden behind a feature flag (not enabled by default) - i.e. default is the "safe" only, and `--features ffi` enables daemons.

**Comment by gquintard** [comment]
ultimately, yes, but as you'll see from the few vmods that use this crate....well, we are not there yet as the Varnish APIs arebig, but that's a goal

**Comment by nyurik** [comment]
Renamed in v0.1.0:

## Rust items

- `COWProbe` struct to `CowProbe`
- `COWRequest` struct to `CowRequest`
- `HTTP` struct to `HttpHeaders`
- `HTTPIter` struct to `HttpHeadersIter`
- `VDPCtx` struct to `DeliveryProcCtx`
- `VDP` trait to `DeliveryProcessor`
- `VFPCtx` struct to `FetchProcCtx`
- `VFP` trait to `FetchProcessor`
- `Vsb` struct to `Buffer`
- `Vsb::cat` function to `Buffer::write`
- `WS` struct to `Workspace`

## Auto-generated items:

* `enum VSL_tag_e` → `VslTag`, removing `SLT_` prefix on enum values, e.g. `SLT_Debug` -> `Debug`
* `enum boc_state_e` → `BocState`, removing `BOS_` prefix on enum values, e.g. `BOS_INVALID` -> `Invalid`
* `enum director_state_e` → `DirectorState`, removing `DIR_S_` prefix on enum values, e.g. `DIR_S_NULL` -> `Null`
* `enum gethdr_e` → `GetHeader`, removing `HDR_` prefix on enum values, e.g. `HDR_REQ_TOP` -> `ReqTop`
* `enum lbody_e` → `Body`, removing `LBODY_` prefix on enum values, e.g. `LBODY_SET_STRING` -> `SetString`
* `enum sess_attr` → `SessionAttr`, removing `SA_` prefix on enum values, e.g. `SA_TRANSPORT` -> `Transport`
* `enum task_prio` → `TaskPriority`, removing `TASK_QUEUE_` prefix on enum values, e.g. `BO` -> `TaskQueueBo`
* `enum vas_e` → `Vas`, removing `VAS_` prefix on enum values, e.g. `VAS_WRONG` -> `Wrong`
* `enum vcl_event_e` → `VclEvent`, removing `VCL_EVENT_` prefix on enum values, e.g. `VCL_EVENT_LOAD` -> `Load`
* `enum vcl_func_call_e` → `VclFuncCall`, removing `VSUB_` prefix on enum values, e.g. `VSUB_STATIC` -> `Static`
* `enum vcl_func_fail_e` → `VclFuncFail`, removing `VSUB_E_` prefix on enum values, e.g. `VSUB_E_OK` -> `Ok`
* `enum vdp_action` → `VdpAction`, removing `VDP_` prefix on enum values, e.g. `VDP_NULL` -> `Null`
* `enum vfp_status` → `VfpStatus`, removing `VFP_` prefix on enum values, e.g. `VFP_ERROR` -> `Error`
