### ISSUE TITLE
Generate vmodtool's .vcc files dynamically using attributes

### ISSUE THREAD

**Issue by nyurik** [gquintard/varnish-rs#42]
It seems .vcc file should be generated dynamically based on some attribute(s) - otherwise it is just a mismatch waiting to happen, and a pain to maintain.

PGRX has a [similar pattern](https://docs.rs/pgrx/latest/pgrx/attr.pg_extern.html) with exposing Rust functions to SQL code:

```rust
#[pg_extern]
fn boop(a: default!(i32, 11111)) { todo!() }
```

### Functions
```
$Function <type> func_name(<params>)
```

* Input type can be any of these types, or an `Option<T>`.
* Output could be either the type `T` or the `Result<T, VarnishError>`. `VarnishError` should probably be an `enum` with a type - e.g. `VarnishError::String(String)` for all supported types (?).
* I am not sure `ctx.fail("...")` (manual fail) adds much value vs the `Result` type.
* `INT` in an example uses i64, but not sure if underlying system supports any other integer types?
* `[INT n]` seems like it should be an `Option<i64>` in Rust, and only applicable to input parameters.
* `PRIV_TASK` and `PRIV_VCL`: I am not certain how this works yet, and how `TASK` differs from `VCL`, or what the rules are for passing it in or out. In the user code, it could be a parameter/output annotated with a special attribute like `#[priv_task]` or `#[priv_vcl]`?
* `PROBE` could be a `Probe` or a `CowProbe` in Rust, and it seems it is input only?

| VCC         | Rust                   |
|-------------|------------------------|
| `VOID`      | `()`                   |
| `BOOL`      | `bool`                 |
| `INT`       | `i64` (?)              |
| `[INT n]`   | `Option<i64>` (?)      |
| `DURATION`  | `std::time::Duration`  |
| `IP`        | `std::net::SocketAddr` | 
| `STRING`    | `&'a str` or `String`  |
| `PRIV_TASK` | `#[task] T`(name?)     |
| `PRIV_VCL`  | `#[vcl] T` (name?)     |
| `PROBE`     | `Probe` or `CowProbe`  |

### Objects
todo

### Events
todo

**Comment by gquintard** [comment]
sooooooooooooo, big topic.

Macro-driven generation would be very nice, but I admit it's outside of my comfort zone at the moment, and `vmodtool.py` does a lot of magic, so coopting it was the easy way out.

for more context: https://github.com/varnishcache/varnish-cache/blob/master/doc/sphinx/reference/vmod.rst

**Comment by nyurik** [comment]
Done! No more .vcc files, macro rulez :)
