### ISSUE TITLE
Consider making `serde` an optional dependency

### ISSUE THREAD

**Issue by nyurik** [gquintard/varnish-rs#47]
From the looks of it, `serde` is not used most of the time - so it might be a good idea to make it optional behind a feature flag. It could still be enabled by default if desired (?), but it would allow projects to speed up compilation by removing it.  Unless i am mistaken, and it is critically important?

**Comment by gquintard** [comment]
I'm only seeing in `probe.rs` and I can't remember a good use case for it, fell free to rip it out

**Comment by nyurik** [comment]
done in #62
