### ISSUE TITLE
change IntoResult to return an actual error rather than String

### ISSUE THREAD

**Issue by gquintard** [gquintard/varnish-rs#8]
current `IntoResult` definition:

```
pub trait IntoResult<E> {
    type Item;
    fn into_result(self) -> Result<Self::Item, String>;
}
```

this should become

```
pub trait IntoResult<E> {
    type Item;
    fn into_result(self) -> Result<Self::Item, Error>;
}
```

so we have better control over error printing.

Incidentally, once this is done, we can update `vmodtool-rs` with an option to control how to log the error with `ctx.fail()`. i.e. we can use `{}`, `{:?}` or `{:#}` which is very convenient with [anyhow](file:///home/gquintard/fun/vmod-reqwest/target/doc/anyhow/struct.Error.html#display-representations)

**Comment by nyurik** [comment]
is this done?

**Comment by gquintard** [comment]
Overtaken By Event (OBE) thanks to all your good work on the macro front
